# Generated by Django 3.1.7 on 2021-07-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_attendancerange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceclass',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=15),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('8:30 - 10:00', '8:30 - 10:00'), ('10:00 - 11:30', '10:00 - 11:30'), ('11:30 - 13:00', '11:30 - 13:00'), ('13:20 - 14:50', '13:20 - 14:50'), ('14:50 - 16:20', '14:50 - 16:20'), ('16:20 - 17:40', '16:20 - 17:40'), ('09:00 - 10:30', '09:00 - 10:30'), ('10:30 - 12:00', '10:30 - 12:00'), ('15:00 - 16:30', '15:00 - 16:30'), ('16:30 - 18:00', '16:30 - 18:00'), ('18:00 - 19:30', '18:00 - 19:30'), ('19:30 - 21:00', '19:30 - 21:00')], default='11:00 - 11:50', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2020-06-01'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(choices=[('Class test 1', 'Class test 1'), ('Class test 2', 'Class test 2'), ('Class test 3', 'Class test 3'), ('Quiz Test', 'Quiz Test'), ('Mid Exam', 'Mid Exam'), ('Semester End Exam', 'Semester End Exam')], default='Class test 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='marksclass',
            name='name',
            field=models.CharField(choices=[('Class test 1', 'Class test 1'), ('Class test 2', 'Class test 2'), ('Class test 3', 'Class test 3'), ('Quiz Test', 'Quiz Test'), ('Mid Exam', 'Mid Exam'), ('Semester End Exam', 'Semester End Exam')], default='Internal test 1', max_length=50),
        ),
    ]
