# Generated by Django 3.1.7 on 2021-06-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20210629_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(choices=[('Class test 1', 'Class test 1'), ('Class test 2', 'Class test 2'), ('Class test 3', 'Class test 3'), ('Event 1', 'Event 1'), ('Event 2', 'Event 2'), ('Semester Final Exam', 'Semester Final Exam')], default='Class test 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='marksclass',
            name='name',
            field=models.CharField(choices=[('Class test 1', 'Class test 1'), ('Class test 2', 'Class test 2'), ('Class test 3', 'Class test 3'), ('Event 1', 'Event 1'), ('Event 2', 'Event 2'), ('Semester Final Exam', 'Semester Final Exam')], default='Class test 1', max_length=50),
        ),
    ]
