# Generated by Django 3.1.7 on 2021-07-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_auto_20210726_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('8:30 - 10:00/09:00 - 10:30', '8:30 - 10:00/09:00 - 10:30'), ('10:00 - 11:30/10:30 - 12:00', '10:00 - 11:30/10:30 - 12:00'), ('11:30 - 13:00', '11:30 - 13:00'), ('13:20 - 14:50', '13:20 - 14:50'), ('14:50 - 16:20/15:00 - 16:30', '14:50 - 16:20/15:00 - 16:30'), ('16:20/16:30 - 18:00 - 17:40', '16:20 - 17:40/16:30 - 18:00'), ('18:00 - 19:30', '18:00 - 19:30'), ('19:30 - 21:00', '19:30 - 21:00')], default='11:00 - 11:50', max_length=50),
        ),
    ]
